name: Feature Request
description: Create a feature request for Datahike
labels: 'enhancement'
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file a feature request! Please fill out this form as completely as possible.
  - type: markdown
    attributes:
      value: 'Feature requests will be converted to the GitHub Discussions "Ideas" section for better community conversations.'
  - type: textarea
    attributes:
      label: Describe the feature you would like to request
      description: A clear and concise description of what you want and what your use case is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you would like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any solutions or features in other databases you have considered.
    validations:
      required: true
