blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/replikativ/datahike/discussions
    about: Do you have specific questions or just want to know more? Hop over to our community at GitHub discussions and ask away! 
  
