version: '3.4'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: datahike
      POSTGRES_PASSWORD: clojure
      POSTGRES_DB: "pg-example"
    ports:
      - "5437:5432"
    volumes:
      - /tmp/datahike_example/data:/var/lib/postgresql/data
